name: Push Workflow

on: [push]

jobs:

  setup-environment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install --upgrade wheel
        make dependencies

    - name: Install Test Dependencies
      run : make test-dependencies

  check-code:

    needs: setup-environment

    steps:
    - name: Check Codestyle
      run: make check-codestyle

    - name: Check Docstyle
      run: make check-docstyle

    - name: Check Security Issues
      run: make check-security